// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'register_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RegisterModel _$RegisterModelFromJson(Map<String, dynamic> json) =>
    RegisterModel(
      odataContext: json['odataContext'] as String?,
      registerValue: (json['value'] as List<dynamic>?)
          ?.map((e) => RegisterValue.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$RegisterModelToJson(RegisterModel instance) =>
    <String, dynamic>{
      'odataContext': instance.odataContext,
      'value': instance.registerValue,
    };

RegisterValue _$RegisterValueFromJson(Map<String, dynamic> json) =>
    RegisterValue(
      id: json['id'] as int,
      guid: json['guid'] as String?,
      sicilNo: json['sicilNo'] as int?,
      sicilKod: json['sicilKod'],
      sicilTipId: json['sicilTipId'] as String?,
      isCari: json['isCari'] as bool?,
      ad: json['ad'],
      soyad: json['soyad'],
      unvan: json['unvan'] as String,
      tcKimlikNo: json['tcKimlikNo'],
      vergiDairesi: json['vergiDairesi'] as String?,
      vergiNumarasi: json['vergiNumarasi'] as int?,
      pasaportNo: json['pasaportNo'],
      cinsiyetLookupId: json['cinsiyetLookupId'] as int?,
      dogumTarih: json['dogumTarih'],
      dogumYer: json['dogumYer'],
      egitimDurumLookupId: json['egitimDurumLookupId'],
      meslekLookupId: json['meslekLookupId'],
      ilisikKesildi: json['ilisikKesildi'],
      cepTelefonu: json['cepTelefonu'] as String?,
      isCepTelefonu: json['isCepTelefonu'],
      ePosta: json['ePosta'] as String?,
      isePosta: json['isePosta'],
      uyrukLookupId: json['uyrukLookupId'],
      varisSicilId: json['varisSicilId'],
      tuzelKisiTipLookupId: json['tuzelKisiTipLookupId'],
      ticaretSicilNo: json['ticaretSicilNo'],
      emeklilikTarih: json['emeklilikTarih'],
      sgkTipLookupId: json['sgkTipLookupId'],
      sgkSicilNo: json['sgkSicilNo'],
      ehliyetTipLookupId: json['ehliyetTipLookupId'],
      ehliyetAldigiYer: json['ehliyetAldigiYer'],
      ehliyetNo: json['ehliyetNo'],
      eskiSicilNo: json['eskiSicilNo'],
      eskiSicilKaynakId: json['eskiSicilKaynakId'],
      olumTarih: json['olumTarih'],
      smsBilgilendirme: json['smsBilgilendirme'],
      ePostaBilgilendirme: json['ePostaBilgilendirme'],
      fizikselArsivDosyaNo: json['fizikselArsivDosyaNo'],
      kepEPosta: json['kepEPosta'],
      tasimaId: json['tasimaId'],
      bagliUstSicilId: json['bagliUstSicilId'],
      icra: json['icra'],
      icraTakip: json['icraTakip'],
      aciklama: json['aciklama'],
      operatorUyarisi: json['operatorUyarisi'],
      webKullaniciUyarisi: json['webKullaniciUyarisi'] as String?,
      babaAdi: json['babaAdi'],
      anneAdi: json['anneAdi'],
      eskiSoyadi: json['eskiSoyadi'],
      medeniDurumLookupId: json['medeniDurumLookupId'],
      kanGrupLookupId: json['kanGrupLookupId'],
      dinLookupId: json['dinLookupId'],
      nfsCuzdanSeriNo: json['nfsCuzdanSeriNo'],
      nfsCuzdanNo: json['nfsCuzdanNo'],
      nfsKayitIlId: json['nfsKayitIlId'],
      nfsKayitIlceId: json['nfsKayitIlceId'],
      nfsKayitMahalle: json['nfsKayitMahalle'],
      nfsCiltNo: json['nfsCiltNo'],
      nfsAileSiraNo: json['nfsAileSiraNo'],
      nfsSiraNo: json['nfsSiraNo'],
      nfsVerilisTarih: json['nfsVerilisTarih'],
      nfsVerilisNedeni: json['nfsVerilisNedeni'],
      nfsVerildigiYer: json['nfsVerildigiYer'],
      nfsKayitYer: json['nfsKayitYer'],
      nfsKayitNo: json['nfsKayitNo'],
      nfsVerildigiIlId: json['nfsVerildigiIlId'],
      nfsVerildigiIlceId: json['nfsVerildigiIlceId'],
      nfsSonGecerlilikTarih: json['nfsSonGecerlilikTarih'],
      kutukIlkTescilTarih: json['kutukIlkTescilTarih'],
      dogumIlId: json['dogumIlId'],
      dogumIlceId: json['dogumIlceId'],
      organizasyonId: json['organizasyonId'],
      gorevYerId: json['gorevYerId'],
      createdUserId: json['createdUserId'] as int?,
      lastUpdatedUserId: json['lastUpdatedUserId'] as int?,
      dataStatus: json['dataStatus'] as String?,
      createdAt: json['createdAt'] as String?,
      lastUpdatedAt: json['lastUpdatedAt'] as String?,
    );

Map<String, dynamic> _$RegisterValueToJson(RegisterValue instance) =>
    <String, dynamic>{
      'id': instance.id,
      'guid': instance.guid,
      'sicilNo': instance.sicilNo,
      'sicilKod': instance.sicilKod,
      'sicilTipId': instance.sicilTipId,
      'isCari': instance.isCari,
      'ad': instance.ad,
      'soyad': instance.soyad,
      'unvan': instance.unvan,
      'tcKimlikNo': instance.tcKimlikNo,
      'vergiDairesi': instance.vergiDairesi,
      'vergiNumarasi': instance.vergiNumarasi,
      'pasaportNo': instance.pasaportNo,
      'cinsiyetLookupId': instance.cinsiyetLookupId,
      'dogumTarih': instance.dogumTarih,
      'dogumYer': instance.dogumYer,
      'egitimDurumLookupId': instance.egitimDurumLookupId,
      'meslekLookupId': instance.meslekLookupId,
      'ilisikKesildi': instance.ilisikKesildi,
      'cepTelefonu': instance.cepTelefonu,
      'isCepTelefonu': instance.isCepTelefonu,
      'ePosta': instance.ePosta,
      'isePosta': instance.isePosta,
      'uyrukLookupId': instance.uyrukLookupId,
      'varisSicilId': instance.varisSicilId,
      'tuzelKisiTipLookupId': instance.tuzelKisiTipLookupId,
      'ticaretSicilNo': instance.ticaretSicilNo,
      'emeklilikTarih': instance.emeklilikTarih,
      'sgkTipLookupId': instance.sgkTipLookupId,
      'sgkSicilNo': instance.sgkSicilNo,
      'ehliyetTipLookupId': instance.ehliyetTipLookupId,
      'ehliyetAldigiYer': instance.ehliyetAldigiYer,
      'ehliyetNo': instance.ehliyetNo,
      'eskiSicilNo': instance.eskiSicilNo,
      'eskiSicilKaynakId': instance.eskiSicilKaynakId,
      'olumTarih': instance.olumTarih,
      'smsBilgilendirme': instance.smsBilgilendirme,
      'ePostaBilgilendirme': instance.ePostaBilgilendirme,
      'fizikselArsivDosyaNo': instance.fizikselArsivDosyaNo,
      'kepEPosta': instance.kepEPosta,
      'tasimaId': instance.tasimaId,
      'bagliUstSicilId': instance.bagliUstSicilId,
      'icra': instance.icra,
      'icraTakip': instance.icraTakip,
      'aciklama': instance.aciklama,
      'operatorUyarisi': instance.operatorUyarisi,
      'webKullaniciUyarisi': instance.webKullaniciUyarisi,
      'babaAdi': instance.babaAdi,
      'anneAdi': instance.anneAdi,
      'eskiSoyadi': instance.eskiSoyadi,
      'medeniDurumLookupId': instance.medeniDurumLookupId,
      'kanGrupLookupId': instance.kanGrupLookupId,
      'dinLookupId': instance.dinLookupId,
      'nfsCuzdanSeriNo': instance.nfsCuzdanSeriNo,
      'nfsCuzdanNo': instance.nfsCuzdanNo,
      'nfsKayitIlId': instance.nfsKayitIlId,
      'nfsKayitIlceId': instance.nfsKayitIlceId,
      'nfsKayitMahalle': instance.nfsKayitMahalle,
      'nfsCiltNo': instance.nfsCiltNo,
      'nfsAileSiraNo': instance.nfsAileSiraNo,
      'nfsSiraNo': instance.nfsSiraNo,
      'nfsVerilisTarih': instance.nfsVerilisTarih,
      'nfsVerilisNedeni': instance.nfsVerilisNedeni,
      'nfsVerildigiYer': instance.nfsVerildigiYer,
      'nfsKayitYer': instance.nfsKayitYer,
      'nfsKayitNo': instance.nfsKayitNo,
      'nfsVerildigiIlId': instance.nfsVerildigiIlId,
      'nfsVerildigiIlceId': instance.nfsVerildigiIlceId,
      'nfsSonGecerlilikTarih': instance.nfsSonGecerlilikTarih,
      'kutukIlkTescilTarih': instance.kutukIlkTescilTarih,
      'dogumIlId': instance.dogumIlId,
      'dogumIlceId': instance.dogumIlceId,
      'organizasyonId': instance.organizasyonId,
      'gorevYerId': instance.gorevYerId,
      'createdUserId': instance.createdUserId,
      'lastUpdatedUserId': instance.lastUpdatedUserId,
      'dataStatus': instance.dataStatus,
      'createdAt': instance.createdAt,
      'lastUpdatedAt': instance.lastUpdatedAt,
    };
